# Generated by Django 3.2.13 on 2023-06-28 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipments', '0003_brandmodel_equipmentmodel_installedbasemodel_modelmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportLevelModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование')),
                ('priority', models.IntegerField(default=0, verbose_name='Приоритет')),
            ],
            options={
                'verbose_name': 'Тип поддержи',
                'verbose_name_plural': 'Тип поддержи',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ContractModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Номер договора')),
                ('dc_address', models.CharField(blank=True, max_length=250, null=True, verbose_name='Адрес ЦОД')),
                ('signed', models.DateField(verbose_name='Начало договора')),
                ('enddate', models.DateField(verbose_name='Окончание договора')),
                ('link', models.CharField(blank=True, max_length=250, null=True, verbose_name='Ссылка на договор')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to=settings.AUTH_USER_MODEL, verbose_name='Заказчик')),
                ('support', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.supportlevelmodel', verbose_name='Тип поддержки')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договоры',
                'ordering': ['number', 'client__organization__name'],
            },
        ),
        migrations.CreateModel(
            name='ContractHistoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250, verbose_name='Текст')),
                ('pubdate', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('contract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.contractmodel', verbose_name='Договор')),
            ],
            options={
                'verbose_name': 'История изменений договора',
                'verbose_name_plural': 'История изменений договоров',
                'ordering': ['-pubdate'],
            },
        ),
        migrations.CreateModel(
            name='ContractEquipmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=50, verbose_name='Серийный номер')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eqcontracts', to='contracts.contractmodel', verbose_name='Договор')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipments.equipmentmodel', verbose_name='Оборудование')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
                'ordering': ['equipment', 'sn'],
            },
        ),
    ]
