# Generated by Django 3.2.13 on 2023-07-12 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractmodel',
            name='end_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='endusers', to=settings.AUTH_USER_MODEL, verbose_name='Конечный пользователь'),
        ),
        migrations.AlterField(
            model_name='contractmodel',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to=settings.AUTH_USER_MODEL, verbose_name='Поставщик'),
        ),
    ]
