# Generated by Django 3.2.13 on 2024-08-19 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_auto_20230712_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractequipmentmodel',
            name='support',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.supportlevelmodel', verbose_name='Тип поддержки'),
        ),
    ]
