# Generated by Django 3.2.13 on 2024-08-19 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_contractequipmentmodel_support'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractmodel',
            name='support',
        ),
    ]
