# Generated by Django 3.2.13 on 2023-04-27 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_telegram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.CharField(default=1, max_length=300, verbose_name='Организация'),
            preserve_default=False,
        ),
    ]
