# Generated by Django 3.2.13 on 2023-05-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_organizationmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationmodel',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Наименование'),
        ),
    ]
