# Generated by Django 3.2.13 on 2023-05-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_organizationmodel_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationmodel',
            options={'ordering': ['name'], 'verbose_name': 'Организация', 'verbose_name_plural': 'Организации'},
        ),
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Организация'),
        ),
    ]
