# Generated by Django 3.2.13 on 2023-05-10 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20230510_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='organizations', to='accounts.organizationmodel', verbose_name='Организация'),
            preserve_default=False,
        ),
    ]
