# Generated by Django 3.2.13 on 2023-05-16 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=300, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254, verbose_name='Адрес электронной почты')),
                ('phone', models.CharField(blank=True, max_length=18, null=True, verbose_name='Телефон')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='accounts.organizationmodel', verbose_name='Контактное лицо')),
            ],
            options={
                'verbose_name': 'Контактное лицо',
                'verbose_name_plural': 'Информация для связи',
            },
        ),
    ]
