# Generated by Django 3.2.13 on 2023-07-18 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_organizationcontactmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationcontactmodel',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='accounts.organizationmodel'),
        ),
    ]
