# Generated by Django 3.2.13 on 2025-01-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_usertokenmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertokenmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='usertokenmodel',
            name='uid',
            field=models.CharField(default=1, max_length=33),
            preserve_default=False,
        ),
    ]
