# Generated by Django 3.2.13 on 2025-01-20 11:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20250120_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertokenmodel',
            name='pubdate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
