# Generated by Django 3.2.13 on 2025-01-20 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_usertokenmodel_pubdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertokenmodel',
            name='uid',
            field=models.CharField(max_length=33, unique=True),
        ),
    ]
