"""
Django settings for integrator project.

Generated by 'django-admin startproject' using Django 3.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import os, sys
from pathlib import Path
from django.conf import global_settings

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
PROJECT_ROOT = os.path.dirname(__file__)
sys.path.insert(0, os.path.join(PROJECT_ROOT, 'apps')) #Приложения в папке "apps"


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-4eu3sxllzyr@-o$*^*+z$7-9s5uosnzl3quw!_k$0+wa62)h+u'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['51.250.54.123', 'sd.myxcloud.ru', 'help.myxcloud.ru']


# Application definition

INSTALLED_APPS = [
    'main.apps.MainConfig',
    'login.apps.LoginConfig',
    'partners.apps.PartnersConfig',
    'services.apps.ServicesConfig',
    'contacts.apps.ContactsConfig',
    'socials.apps.SocialsConfig',
    'applications.apps.ApplicationsConfig',
    'equipments.apps.EquipmentsConfig',
    'spares.apps.SparesConfig',
    'contracts.apps.ContractsConfig',
    'accounts.apps.AccountsConfig',
    'articles.apps.ArticlesConfig',
    'admin.apps.AdminConfig',
    'ckeditor',
    # 'nested_admin',
    # 'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'sorl.thumbnail',
    'django_select2',
    'rest_framework',
    'drf_spectacular',
    'django_filters',
    'django_cleanup.apps.CleanupConfig', #Должно быть последним
]

SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'integrator.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(PROJECT_ROOT, 'templates')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'main.context_processors.NotificationsView',
            ],
        },
    },
]

WSGI_APPLICATION = 'integrator.wsgi.application'

AUTH_USER_MODEL = 'accounts.User'
AUTHENTICATION_BACKENDS = ['accounts.backends.EmailBackend']

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'integrator',
        'USER': 'integrator',
        'PASSWORD': '#G687mwLhH0V',
        'HOST': 'localhost',   # Or an IP Address that your DB is hosted on
        'PORT': '3306',
        'OPTIONS': {'charset': 'utf8mb4'},
    }
}

TELEGRAM = {
    'bot_token': '5658153963:AAFWWxEqNheGSuOdT0I2PvWgieF1wqkGiWU',
    'channel_id': '-1001561231917',
}

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
        'drf_excel.renderers.XLSXRenderer',
    ],
    'DATE_INPUT_FORMATS': ['%d.%m.%Y'],
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Post API", # название проекта
    "VERSION": "0.0.1", # версия проекта
    # "SERVE_INCLUDE_SCHEMA": False, # исключить эндпоинт /schema
    "SWAGGER_UI_SETTINGS": {
        "filter": True, # включить поиск по тегам
        'deepLinking': True,
        # 'defaultModelExpandDepth': 2,
        # 'defaultModelsExpandDepth': 2,
        # "displayOperationId": True,
    },
    "COMPONENT_SPLIT_REQUEST": True,
    'SORT_OPERATION_PARAMETERS': False,
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LOGIN_URL = '/user_login/'
# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'ru-RU'

TIME_ZONE = 'Europe/Moscow'
DATE_FORMAT = 'd.m.Y'

USE_I18N = True

USE_L10N = True

USE_TZ = True

#Captcha
CAPTCHA_FONT_SIZE = 30
CAPTCHA_LENGTH = 7


EMAIL_HOST = 'smtp.yandex.ru'
EMAIL_HOST_IMAP = 'imap.yandex.ru'
EMAIL_HOST_USER = 'no-reply@myxcloud.ru'
EMAIL_HOST_PASSWORD = 'fiywftbcixydxfij'
EMAIL_PORT = 465
EMAIL_USE_TLS = False
EMAIL_USE_SSL = True
SERVER_EMAIL = EMAIL_HOST_USER
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

DATA_UPLOAD_MAX_MEMORY_SIZE = 52428800
DATA_UPLOAD_MAX_NUMBER_FIELDS = None


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/media/'
STATIC_ROOT = os.path.join(BASE_DIR, "static/")
MEDIA_ROOT = os.path.join(BASE_DIR, "media/")

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REDIS related settings
REDIS_HOST = 'localhost'
REDIS_PORT = '6379'
BROKER_URL = 'redis://' + REDIS_HOST + ':' + REDIS_PORT + '/0'
BROKER_TRANSPORT_OPTIONS = {'visibility_timeout': 3600}
CELERY_RESULT_BACKEND = 'redis://' + REDIS_HOST + ':' + REDIS_PORT + '/0'


CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'Custom',
        'toolbar_Custom': [
            ['Format', 'FontSize', 'Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript',],
            ['RemoveFormat',],
            ['JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock',],
            ['TextColor', 'BGColor',],
            ['NumberedList', 'BulletedList',],
            ['Indent', 'Outdent', 'Blockquote', ],
            ['Link', 'Unlink'],
            ['Table',],
            ['Undo', 'Redo',],
            ['Source']
        ],
        'extraPlugins': ','.join(
            ['font',]
        ),
        'fontSize_sizes': '12/0.75em;14/0.875em;16/1em;18/1.125em;20/1.25em;22/1.375em;24/1.5em;',
        'width': '100%',
        'removePlugins': 'exportpdf',
    },
    'small': {
        'toolbar': 'Custom',
        'toolbar_Custom': [
            ['FontSize', 'Bold', 'Italic', 'Underline', 'Strike','Subscript','Superscript'],
            ['RemoveFormat'],
            ['JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock'],
            ['TextColor',],
            ['BulletedList', 'NumberedList'],
            ['Indent', 'Outdent', 'Blockquote'],
            ['Link', 'Unlink'],
            ['Undo', 'Redo'],
            ['Source']
        ],
        'width': '100%',
        'removePlugins': 'exportpdf',
    },
}
