# Generated by Django 3.2.13 on 2022-09-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('type', models.CharField(default='contacts', editable=False, max_length=8, primary_key=True, serialize=False, verbose_name='Контакты')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование')),
                ('address', models.CharField(max_length=300, verbose_name='Адрес')),
                ('code', models.CharField(max_length=50, verbose_name='Код')),
                ('phone', models.CharField(max_length=18, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
