# Generated by Django 3.2.13 on 2022-09-26 09:53

from django.db import migrations, models
import integrator.apps.validators
import services.models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование услуги')),
                ('description', models.TextField(verbose_name='Описание услуги')),
                ('img', sorl.thumbnail.fields.ImageField(upload_to=services.models.file_name, validators=[integrator.apps.validators.validate_img], verbose_name='Фотография')),
                ('priority', models.IntegerField(default=0, verbose_name='Приоритет')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Сведения об услугах',
                'ordering': ['priority', 'name'],
            },
        ),
    ]
