# Generated by Django 3.2.13 on 2022-09-26 09:53

from django.db import migrations, models
import integrator.apps.validators
import socials.models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование сети')),
                ('img', sorl.thumbnail.fields.ImageField(upload_to=socials.models.file_name, validators=[integrator.apps.validators.validate_img], verbose_name='Логотип')),
                ('link', models.CharField(blank=True, max_length=300, null=True, verbose_name='Ссылка')),
                ('priority', models.IntegerField(default=0, verbose_name='Приоритет')),
            ],
            options={
                'verbose_name': 'Социальная сеть',
                'verbose_name_plural': 'Социальнаые сети',
                'ordering': ['priority', 'name'],
            },
        ),
    ]
