# Generated by Django 3.2.13 on 2023-05-23 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0002_vendormodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Бренд оборудования',
                'verbose_name_plural': 'Бренды оборудования',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ModelModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brands', to='equipments.brandmodel', verbose_name='Бренд')),
            ],
            options={
                'verbose_name': 'Модель оборудования',
                'verbose_name_plural': 'Модели оборудования',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eqbrands', to='equipments.brandmodel', verbose_name='Бренд')),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='models', to='equipments.modelmodel', verbose_name='Модель')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eqtypes', to='equipments.typemodel', verbose_name='Тип')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors', to='equipments.vendormodel', verbose_name='Вендор')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
                'ordering': ['brand', 'model'],
            },
        ),
        migrations.CreateModel(
            name='InstalledBaseModel',
            fields=[
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Инсталлированная база',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('equipments.equipmentmodel',),
        ),
    ]
