# Generated by Django 3.2.13 on 2023-07-12 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0003_brandmodel_equipmentmodel_installedbasemodel_modelmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelmodel',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipments.vendormodel', verbose_name='Вендор'),
        ),
    ]
