# Generated by Django 3.2.13 on 2024-08-15 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0005_auto_20230801_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportLevelModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование')),
                ('priority', models.IntegerField(default=0, verbose_name='Приоритет')),
            ],
            options={
                'verbose_name': 'Тип поддержи',
                'verbose_name_plural': 'Тип поддержи',
                'ordering': ['priority', 'name'],
            },
        ),
    ]
