# Generated by Django 3.2.13 on 2024-08-15 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0006_supportlevelmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentmodel',
            name='support',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipments.supportlevelmodel', verbose_name='Тип поддержки'),
        ),
    ]
