# Generated by Django 3.2.13 on 2024-08-19 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0007_equipmentmodel_support'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentmodel',
            name='support',
        ),
    ]
