# Generated by Django 3.2.13 on 2024-08-19 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0008_remove_equipmentmodel_support'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SupportLevelModel',
        ),
    ]
