# Generated by Django 3.2.13 on 2023-09-21 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleModel',
        ),
    ]
