# Generated by Django 3.2.13 on 2023-09-21 17:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0002_delete_articlemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('number', models.CharField(max_length=250, verbose_name='Номер статьи')),
                ('header', models.CharField(max_length=250, verbose_name='Заголовок статьи')),
                ('level', models.CharField(max_length=250, verbose_name='Уровень статьи')),
                ('symptoms', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Симптомы')),
                ('info', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Доп. информация')),
                ('pubdate', models.CharField(max_length=15, verbose_name='Дата публикации')),
                ('version', models.CharField(max_length=5, verbose_name='Версия')),
                ('type', models.CharField(max_length=100, verbose_name='Тип статьи')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['number', 'title'],
            },
        ),
    ]
