# Generated by Django 3.2.13 on 2023-09-21 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20230921_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='level',
            field=models.TextField(verbose_name='Уровень статьи'),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='number',
            field=models.TextField(verbose_name='Номер статьи'),
        ),
    ]
