# Generated by Django 3.2.13 on 2023-09-22 07:31

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20230921_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlemodel',
            name='info',
        ),
        migrations.RemoveField(
            model_name='articlemodel',
            name='level',
        ),
        migrations.RemoveField(
            model_name='articlemodel',
            name='symptoms',
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Статус публикации'),
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='summary',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Содержание'),
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Информация'),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='header',
            field=models.CharField(max_length=250, verbose_name='Заголовок статьи'),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='number',
            field=models.CharField(max_length=10, verbose_name='Номер статьи'),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='pubdate',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип статьи'),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='version',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Версия'),
        ),
    ]
