# Generated by Django 3.2.13 on 2023-09-25 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20230922_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='title',
            field=models.TextField(verbose_name='Заголовок'),
        ),
    ]
