# Generated by Django 3.2.13 on 2023-09-25 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_alter_articlemodel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='header',
            field=models.TextField(verbose_name='Заголовок статьи'),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='summary',
            field=models.TextField(blank=True, null=True, verbose_name='Содержание'),
        ),
    ]
