# Generated by Django 3.2.13 on 2023-09-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20230925_1042'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='articlemodel',
            index=models.Index(fields=['id'], name='articles_ar_id_a470d0_idx'),
        ),
    ]
