# Generated by Django 3.2.13 on 2023-09-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_articlemodel_articles_ar_id_a470d0_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='articlemodel',
            index=models.Index(fields=['number'], name='articles_ar_number_5bef75_idx'),
        ),
        migrations.AddIndex(
            model_name='articlemodel',
            index=models.Index(fields=['title'], name='articles_ar_title_ab8a83_idx'),
        ),
    ]
