# Generated by Django 3.2.13 on 2023-10-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_articleattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='attachments',
            field=models.TextField(blank=True, null=True, verbose_name='Прикрепленные файлы'),
        ),
        migrations.DeleteModel(
            name='ArticleAttachment',
        ),
    ]
