# Generated by Django 3.2.13 on 2023-10-05 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_auto_20231003_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='products',
            field=models.TextField(blank=True, null=True, verbose_name='Связанные продукты'),
        ),
    ]
