# Generated by Django 3.2.13 on 2023-10-09 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_articlemodel_products'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='articlemodel',
            index=models.Index(fields=['header'], name='articles_ar_header_acc7b8_idx'),
        ),
        migrations.AddIndex(
            model_name='articlemodel',
            index=models.Index(fields=['summary'], name='articles_ar_summary_4b7239_idx'),
        ),
        migrations.AddIndex(
            model_name='articlemodel',
            index=models.Index(fields=['text'], name='articles_ar_text_cee7e1_idx'),
        ),
        migrations.AddIndex(
            model_name='articlemodel',
            index=models.Index(fields=['products'], name='articles_ar_product_a9ae3e_idx'),
        ),
    ]
