# Generated by Django 3.2.13 on 2022-09-26 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_contracthistorymodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentmodel',
            name='client',
        ),
        migrations.AddField(
            model_name='equipmentmodel',
            name='contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eqcontracts', to='applications.contractmodel', verbose_name='Договор'),
        ),
    ]
