# Generated by Django 3.2.13 on 2022-09-27 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_auto_20220926_1048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contracthistorymodel',
            options={'ordering': ['-pubdate'], 'verbose_name': 'История изменений договора', 'verbose_name_plural': 'История изменений договоров'},
        ),
        migrations.AlterField(
            model_name='equipmentmodel',
            name='contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eqcontracts', to='applications.contractmodel', verbose_name='Договор'),
        ),
        migrations.AlterField(
            model_name='equipmentmodel',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors', to='applications.vendormodel', verbose_name='Вендор'),
        ),
    ]
