# Generated by Django 3.2.13 on 2022-09-27 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_supportlevelmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentmodel',
            name='support',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supports', to='applications.supportlevelmodel', verbose_name='Уровень поддержки'),
        ),
    ]
