# Generated by Django 3.2.13 on 2022-09-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_equipmentmodel_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentmodel',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Место расположения (адрес)'),
        ),
    ]
