# Generated by Django 3.2.13 on 2022-09-28 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0007_equipmentmodel_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationmodel',
            options={'ordering': ['status', '-pubdate'], 'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.CreateModel(
            name='ApplicationArchiveModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.TextField(verbose_name='Описание проблемы')),
                ('fio', models.CharField(max_length=250, verbose_name='ФИО заказчика')),
                ('email', models.CharField(max_length=100, verbose_name='Электронная почта заказчика')),
                ('phone', models.CharField(max_length=18, verbose_name='Телефон заказчика')),
                ('pubdate', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('old_id', models.IntegerField(verbose_name='Идентификатор заявки')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archclients', to=settings.AUTH_USER_MODEL, verbose_name='Заказчик')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archcreators', to=settings.AUTH_USER_MODEL, verbose_name='Создано')),
                ('engineer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archengineers', to=settings.AUTH_USER_MODEL, verbose_name='Инженер')),
                ('equipment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archequipments', to='applications.equipmentmodel', verbose_name='Оборудование')),
                ('priority', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archpriorities', to='applications.appprioritymodel', verbose_name='Приоритет заявки')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='applications.statusmodel', verbose_name='Статус заявки')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Архив заявок',
                'ordering': ['-pubdate'],
            },
        ),
    ]
