# Generated by Django 3.2.13 on 2022-09-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_auto_20220928_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationarchivemodel',
            name='pubdate',
            field=models.DateTimeField(verbose_name='Дата создания'),
        ),
    ]
