# Generated by Django 3.2.13 on 2022-09-29 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_auto_20220928_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpareModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=50, unique=True, verbose_name='Серийный номер')),
                ('account', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер счета')),
                ('contract', models.CharField(blank=True, max_length=100, null=True, verbose_name='Договор')),
                ('place', models.CharField(blank=True, max_length=50, null=True, verbose_name='Место на складе')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spbrands', to='applications.brandmodel', verbose_name='Бренд')),
                ('equipment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spequips', to='applications.equipmentmodel', verbose_name='Оборудование')),
            ],
            options={
                'verbose_name': 'ЗИП',
                'verbose_name_plural': 'ЗИП',
                'ordering': ['brand', 'model', 'sn'],
            },
        ),
        migrations.CreateModel(
            name='SpareTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Тип запчасти',
                'verbose_name_plural': 'Типы запчастей',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SparePNModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер партии')),
                ('spare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pnspare', to='applications.sparemodel', verbose_name='Запчасть')),
            ],
            options={
                'verbose_name': 'Номер партии',
                'verbose_name_plural': 'Номера партий',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='SpareNameModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spnbrands', to='applications.brandmodel', verbose_name='Бренд')),
            ],
            options={
                'verbose_name': 'Наименование запчасти',
                'verbose_name_plural': 'Наименование запчастей',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='sparemodel',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spmodels', to='applications.sparenamemodel', verbose_name='Наименование'),
        ),
        migrations.AddField(
            model_name='sparemodel',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spprovider', to='applications.providermodel', verbose_name='Поставщик'),
        ),
        migrations.AddField(
            model_name='sparemodel',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spstatus', to='applications.equipmentstatusmodel', verbose_name='Состояние'),
        ),
        migrations.AddField(
            model_name='sparemodel',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spstock', to='applications.stockmodel', verbose_name='Склад'),
        ),
        migrations.AddField(
            model_name='sparemodel',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sptypes', to='applications.sparetypemodel', verbose_name='Тип'),
        ),
        migrations.CreateModel(
            name='SpareCompatibleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cmpequips', to='applications.equipmentmodel', verbose_name='Оборудование')),
                ('spare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cmpspare', to='applications.sparemodel', verbose_name='Запчасть')),
            ],
            options={
                'verbose_name': 'Совместимое оборудование',
                'verbose_name_plural': 'Совместимое оборудование',
                'ordering': ['spare'],
            },
        ),
    ]
