# Generated by Django 3.2.13 on 2022-09-29 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_auto_20220929_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparemodel',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Количество'),
        ),
    ]
