# Generated by Django 3.2.13 on 2022-09-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0012_sparemodel_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparemodel',
            name='sn',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Серийный номер'),
        ),
    ]
