# Generated by Django 3.2.13 on 2022-09-30 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0013_alter_sparemodel_sn'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sparemodel',
            options={'ordering': ['type', 'brand', 'model', 'sn'], 'verbose_name': 'ЗИП', 'verbose_name_plural': 'ЗИП'},
        ),
        migrations.CreateModel(
            name='AppSpareModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubdate', models.DateTimeField(auto_now_add=True, verbose_name='Дата записи')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeqspare', to='applications.applicationmodel', verbose_name='Заявка')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appspauthors', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('spare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appspare', to='applications.sparemodel', verbose_name='Запчасть')),
            ],
        ),
    ]
