# Generated by Django 3.2.13 on 2022-10-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0014_auto_20220930_0945'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sparepnmodel',
            options={'ordering': ['number'], 'verbose_name': 'Партномер', 'verbose_name_plural': 'Партномера'},
        ),
        migrations.AlterField(
            model_name='apphistorymodel',
            name='type',
            field=models.IntegerField(choices=[(1, 'Изменение статуса'), (2, 'Изменение значения поля'), (3, 'Отправка сообщения на адрес электронной почты'), (4, 'Отправка сообщения в телеграм-канал'), (5, 'Списание запчасти')], verbose_name='Тип события'),
        ),
        migrations.AlterField(
            model_name='sparepnmodel',
            name='number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Партномер'),
        ),
    ]
