# Generated by Django 3.2.13 on 2022-10-06 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0015_auto_20221006_1028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appsparemodel',
            options={'ordering': ['-pubdate'], 'verbose_name': 'История ЗИП', 'verbose_name_plural': 'История ЗИП'},
        ),
        migrations.AlterField(
            model_name='applicationarchivemodel',
            name='old_id',
            field=models.IntegerField(verbose_name='Номер заявки'),
        ),
        migrations.AlterField(
            model_name='appsparemodel',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appspauthors', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
