# Generated by Django 3.2.13 on 2022-10-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0016_auto_20221006_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentmodel',
            name='warranty',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания гарантийного периода'),
        ),
    ]
