# Generated by Django 3.2.13 on 2022-10-12 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0017_alter_equipmentmodel_warranty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractmodel',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to=settings.AUTH_USER_MODEL, verbose_name='Контактное лицо'),
        ),
    ]
