# Generated by Django 3.2.13 on 2022-10-13 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0019_auto_20221013_0732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentmodel',
            name='place',
        ),
        migrations.RemoveField(
            model_name='equipmentmodel',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='equipmentmodel',
            name='status',
        ),
        migrations.RemoveField(
            model_name='equipmentmodel',
            name='stock',
        ),
    ]
