# Generated by Django 3.2.13 on 2022-10-13 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0021_equipmentconfigmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentconfigmodel',
            name='contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='confcontracts', to='applications.contractmodel', verbose_name='Договор'),
        ),
        migrations.AlterField(
            model_name='contractmodel',
            name='executor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executors', to='applications.executormodel', verbose_name='Исполнитель'),
        ),
    ]
