# Generated by Django 3.2.13 on 2022-10-14 06:07

import applications.models
from django.db import migrations, models
import django.db.models.deletion
import integrator.apps.validators


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0023_remove_equipmentconfigmodel_contract'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractDocumentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to=applications.models.file_contract, validators=[integrator.apps.validators.validate_format, integrator.apps.validators.validate_size_20], verbose_name='Файл')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractdocs', to='applications.contractmodel', verbose_name='Договор')),
            ],
            options={
                'verbose_name': 'Файл договора',
                'verbose_name_plural': 'Файлы договоров',
            },
        ),
    ]
