# Generated by Django 3.2.13 on 2022-10-17 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0024_contractdocumentmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparemodel',
            name='equipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spequips', to='applications.modelmodel', verbose_name='Оборудование'),
        ),
    ]
