# Generated by Django 3.2.13 on 2022-10-17 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0025_alter_sparemodel_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparecompatiblemodel',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cmpequips', to='applications.modelmodel', verbose_name='Оборудование'),
        ),
    ]
