# Generated by Django 3.2.13 on 2022-10-24 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0026_alter_sparecompatiblemodel_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationmodel',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appclients', to=settings.AUTH_USER_MODEL, verbose_name='Заказчик'),
        ),
        migrations.AlterField(
            model_name='applicationmodel',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='creators', to=settings.AUTH_USER_MODEL, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='applicationmodel',
            name='engineer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='engineers', to=settings.AUTH_USER_MODEL, verbose_name='Инженер'),
        ),
        migrations.AlterField(
            model_name='applicationmodel',
            name='equipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipments', to='applications.equipmentmodel', verbose_name='Оборудование'),
        ),
        migrations.AlterField(
            model_name='applicationmodel',
            name='priority',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='priorities', to='applications.appprioritymodel', verbose_name='Приоритет заявки'),
        ),
        migrations.AlterField(
            model_name='applicationmodel',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='applications.statusmodel', verbose_name='Статус заявки'),
        ),
    ]
