# Generated by Django 3.2.13 on 2022-10-25 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0027_auto_20221024_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appdocumentsmodel',
            name='name',
            field=models.CharField(blank=True, max_length=300, verbose_name='Наименование файла'),
        ),
    ]
