# Generated by Django 3.2.13 on 2022-11-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0028_alter_appdocumentsmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apphistorymodel',
            name='type',
            field=models.IntegerField(choices=[(1, 'Изменение статуса'), (2, 'Изменение значения поля'), (3, 'Отправка сообщения на адрес электронной почты'), (4, 'Отправка сообщения в телеграм-канал'), (5, 'Списание запчасти'), (6, 'Возврат запчасти')], verbose_name='Тип события'),
        ),
    ]
