# Generated by Django 3.2.13 on 2022-11-01 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0029_alter_apphistorymodel_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Контактное лицо')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='applications.contractmodel', verbose_name='Договор')),
            ],
            options={
                'verbose_name': 'Контактное лицо',
                'verbose_name_plural': 'Список контактных лиц',
            },
        ),
    ]
