# Generated by Django 3.2.13 on 2022-11-01 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0030_contractcontactmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationarchivemodel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='applicationarchivemodel',
            name='fio',
        ),
        migrations.RemoveField(
            model_name='applicationarchivemodel',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='applicationmodel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='applicationmodel',
            name='fio',
        ),
        migrations.RemoveField(
            model_name='applicationmodel',
            name='phone',
        ),
        migrations.AddField(
            model_name='applicationarchivemodel',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archcontact', to=settings.AUTH_USER_MODEL, verbose_name='Контактное лицо'),
        ),
        migrations.AddField(
            model_name='applicationmodel',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appcontact', to=settings.AUTH_USER_MODEL, verbose_name='Контактное лицо'),
        ),
    ]
