# Generated by Django 3.2.13 on 2022-11-01 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0031_auto_20221101_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationmodel',
            name='contact',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='appcontact', to='accounts.user', verbose_name='Контактное лицо'),
            preserve_default=False,
        ),
    ]
