# Generated by Django 3.2.13 on 2022-11-03 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0033_apphistoryviewedmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apphistoryviewedmodel',
            name='history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed', to='applications.apphistorymodel', verbose_name='Событие'),
        ),
        migrations.AlterUniqueTogether(
            name='apphistoryviewedmodel',
            unique_together={('user', 'history')},
        ),
    ]
