# Generated by Django 3.2.13 on 2022-11-16 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0034_auto_20221103_0958'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationmodel',
            options={'ordering': ['id'], 'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
    ]
