# Generated by Django 3.2.13 on 2022-11-18 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0036_alter_applicationmodel_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContractContactModel',
        ),
    ]
