# Generated by Django 3.2.13 on 2022-11-18 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0038_contractcontactmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationmodel',
            name='contact',
        ),
    ]
