# Generated by Django 3.2.13 on 2022-11-18 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0041_alter_applicationmodel_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationarchivemodel',
            name='contact',
        ),
    ]
