# Generated by Django 3.2.13 on 2022-11-18 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0042_remove_applicationarchivemodel_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationarchivemodel',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archcontact', to='applications.contractcontactmodel', verbose_name='Контактное лицо'),
        ),
    ]
