# Generated by Django 3.2.13 on 2023-02-02 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0044_auto_20230118_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparemodel',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spbrands', to='applications.brandmodel', verbose_name='Вендор'),
        ),
        migrations.AlterField(
            model_name='sparemodel',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spmodels', to='applications.sparenamemodel', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='sparemodel',
            name='sn',
            field=models.CharField(default=1, max_length=50, verbose_name='Серийный номер'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sparemodel',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sptypes', to='applications.sparetypemodel', verbose_name='Тип запчасти'),
        ),
    ]
