# Generated by Django 3.2.13 on 2023-02-02 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0045_auto_20230202_0642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sparemodel',
            name='account',
        ),
        migrations.RemoveField(
            model_name='sparemodel',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='sparemodel',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='sparemodel',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='sparemodel',
            name='status',
        ),
    ]
