# Generated by Django 3.2.13 on 2023-02-02 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0046_auto_20230202_0646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sparemodel',
            name='equipment',
        ),
    ]
