# Generated by Django 3.2.13 on 2023-02-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0050_auto_20230202_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparemodel',
            name='barcode',
            field=models.ImageField(blank=True, upload_to='barcodes/'),
        ),
    ]
