# Generated by Django 3.2.13 on 2023-04-20 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0051_sparemodel_barcode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractcontactmodel',
            options={'verbose_name': 'Контактное лицо', 'verbose_name_plural': 'Информация для связи'},
        ),
        migrations.AlterField(
            model_name='contractcontactmodel',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Адрес электронной почты'),
        ),
        migrations.AlterField(
            model_name='contractmodel',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to=settings.AUTH_USER_MODEL, verbose_name='Ответсвенное лицо'),
        ),
    ]
