# Generated by Django 3.2.13 on 2023-04-27 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0053_installedbasemodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='installedbasemodel',
            options={'verbose_name': 'Оборудование', 'verbose_name_plural': 'Инсталлированная база'},
        ),
    ]
