# Generated by Django 3.2.13 on 2023-05-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0054_alter_installedbasemodel_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sparenamemodel',
            name='brand',
        ),
        migrations.AlterModelOptions(
            name='sparemodel',
            options={'ordering': ['name', 'sn'], 'verbose_name': 'ЗИП', 'verbose_name_plural': 'ЗИП'},
        ),
        migrations.AlterModelOptions(
            name='sparepartnumbermodel',
            options={'ordering': ['number'], 'verbose_name': 'Партномер', 'verbose_name_plural': 'Список партномеров'},
        ),
        migrations.RemoveField(
            model_name='sparemodel',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='sparemodel',
            name='model',
        ),
        migrations.RemoveField(
            model_name='sparemodel',
            name='note',
        ),
        migrations.RemoveField(
            model_name='sparemodel',
            name='place',
        ),
        migrations.RemoveField(
            model_name='sparemodel',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='sparemodel',
            name='type',
        ),
        migrations.RemoveField(
            model_name='sparepartnumbermodel',
            name='model',
        ),
        migrations.AddField(
            model_name='sparemodel',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='sparemodel',
            name='name',
            field=models.CharField(default='old', max_length=250, verbose_name='Наименование'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SpareCompatibleModel',
        ),
        migrations.DeleteModel(
            name='SpareNameModel',
        ),
        migrations.DeleteModel(
            name='SpareTypeModel',
        ),
        migrations.DeleteModel(
            name='StockModel',
        ),
    ]
