# Generated by Django 3.2.13 on 2023-05-12 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0055_auto_20230512_1614'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentmodel',
            options={'ordering': ['brand', 'model'], 'verbose_name': 'Оборудование', 'verbose_name_plural': 'Оборудование'},
        ),
        migrations.RemoveField(
            model_name='equipmentmodel',
            name='account',
        ),
        migrations.RemoveField(
            model_name='equipmentmodel',
            name='address',
        ),
        migrations.RemoveField(
            model_name='equipmentmodel',
            name='note',
        ),
        migrations.RemoveField(
            model_name='equipmentmodel',
            name='sn',
        ),
        migrations.RemoveField(
            model_name='equipmentmodel',
            name='support',
        ),
        migrations.RemoveField(
            model_name='equipmentmodel',
            name='warranty',
        ),
    ]
