# Generated by Django 3.2.13 on 2023-05-16 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_organizationcontactmodel'),
        ('applications', '0057_alter_supportlevelmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationarchivemodel',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archcontact', to='accounts.organizationcontactmodel', verbose_name='Контактное лицо'),
        ),
        migrations.AlterField(
            model_name='applicationmodel',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appcontact', to='accounts.organizationcontactmodel', verbose_name='Контактное лицо'),
        ),
        migrations.DeleteModel(
            name='ContractContactModel',
        ),
    ]
