# Generated by Django 3.2.13 on 2023-05-16 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0058_auto_20230516_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractmodel',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to=settings.AUTH_USER_MODEL, verbose_name='Заказчик'),
        ),
        migrations.DeleteModel(
            name='ContractDocumentModel',
        ),
    ]
