# Generated by Django 3.2.13 on 2023-05-16 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0059_auto_20230516_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractmodel',
            name='executor',
        ),
        migrations.RemoveField(
            model_name='equipmentmodel',
            name='contract',
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='link',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Ссылка на договор'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='support',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='applications.supportlevelmodel', verbose_name='Тип поддержки'),
        ),
        migrations.AlterField(
            model_name='contracthistorymodel',
            name='text',
            field=models.CharField(max_length=250, verbose_name='Текст'),
        ),
        migrations.CreateModel(
            name='ContractEquipmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=50, verbose_name='Серийный номер')),
                ('dc_address', models.CharField(blank=True, max_length=250, null=True, verbose_name='Адрес ЦОД')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eqcontracts', to='applications.contractmodel', verbose_name='Договор')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.equipmentmodel', verbose_name='Оборудование')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
                'ordering': ['equipment', 'sn'],
            },
        ),
    ]
