# Generated by Django 3.2.13 on 2023-05-17 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0060_auto_20230516_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractequipmentmodel',
            name='dc_address',
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='dc_address',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Адрес ЦОД'),
        ),
    ]
