# Generated by Django 3.2.13 on 2023-05-23 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0061_auto_20230517_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sparepnmodel',
            name='number',
        ),
        migrations.RemoveField(
            model_name='sparepnmodel',
            name='spare',
        ),
        migrations.DeleteModel(
            name='SparePartNumberModel',
        ),
        migrations.DeleteModel(
            name='SparePNModel',
        ),
    ]
