# Generated by Django 3.2.13 on 2023-05-23 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0062_auto_20230523_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentmodel',
            name='type',
        ),
        migrations.DeleteModel(
            name='EquipmentTypeModel',
        ),
    ]
