# Generated by Django 3.2.13 on 2023-05-23 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0063_auto_20230523_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentmodel',
            name='vendor',
        ),
        migrations.DeleteModel(
            name='VendorModel',
        ),
    ]
