# Generated by Django 3.2.13 on 2023-05-23 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0064_auto_20230523_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentmodel',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='equipmentmodel',
            name='model',
        ),
        migrations.RemoveField(
            model_name='modelmodel',
            name='brand',
        ),
        migrations.DeleteModel(
            name='InstalledBaseModel',
        ),
        migrations.AlterModelOptions(
            name='contractequipmentmodel',
            options={'verbose_name': 'Оборудование', 'verbose_name_plural': 'Оборудование'},
        ),
        migrations.RemoveField(
            model_name='applicationarchivemodel',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='applicationmodel',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='contractequipmentmodel',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='equipmentconfigmodel',
            name='equipment',
        ),
        migrations.DeleteModel(
            name='BrandModel',
        ),
        migrations.DeleteModel(
            name='EquipmentModel',
        ),
        migrations.DeleteModel(
            name='ModelModel',
        ),
    ]
