# Generated by Django 3.2.13 on 2023-06-27 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spares', '0002_sparemodel_sparepnmodel'),
        ('applications', '0065_auto_20230523_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsparemodel',
            name='spare',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appspare', to='spares.sparemodel', verbose_name='Запчасть'),
        ),
        migrations.DeleteModel(
            name='SpareModel',
        ),
    ]
