# Generated by Django 3.2.13 on 2023-06-28 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0066_auto_20230627_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contracthistorymodel',
            name='author',
        ),
        migrations.RemoveField(
            model_name='contracthistorymodel',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='contractmodel',
            name='client',
        ),
        migrations.RemoveField(
            model_name='contractmodel',
            name='support',
        ),
        migrations.DeleteModel(
            name='ContractEquipmentModel',
        ),
        migrations.DeleteModel(
            name='ContractHistoryModel',
        ),
        migrations.DeleteModel(
            name='ContractModel',
        ),
        migrations.DeleteModel(
            name='SupportLevelModel',
        ),
    ]
