# Generated by Django 3.2.13 on 2023-07-13 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0004_modelmodel_vendor'),
        ('applications', '0067_auto_20230628_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationarchivemodel',
            name='equipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archequipments', to='equipments.equipmentmodel', verbose_name='Оборудование'),
        ),
        migrations.AddField(
            model_name='applicationmodel',
            name='equipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipments', to='equipments.equipmentmodel', verbose_name='Оборудование'),
        ),
        migrations.AddField(
            model_name='equipmentconfigmodel',
            name='equipment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='equipconf', to='equipments.equipmentmodel', verbose_name='Оборудование'),
            preserve_default=False,
        ),
    ]
