# Generated by Django 3.2.13 on 2023-07-18 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_auto_20230712_1527'),
        ('applications', '0068_auto_20230713_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationmodel',
            name='equipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipments', to='contracts.contractequipmentmodel', verbose_name='Оборудование'),
        ),
    ]
