# Generated by Django 3.2.13 on 2023-09-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0069_alter_applicationmodel_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appcommentmodel',
            name='display',
            field=models.BooleanField(default=False, verbose_name='Скрыть комментарий от клиента'),
        ),
    ]
