# Generated by Django 3.2.13 on 2023-09-28 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0070_appcommentmodel_display'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appcommentmodel',
            old_name='display',
            new_name='hide',
        ),
    ]
