# Generated by Django 3.2.13 on 2023-11-22 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0071_rename_display_appcommentmodel_hide'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationmodel',
            name='changed',
            field=models.BooleanField(default=False, verbose_name='Оборудование изменено'),
        ),
    ]
