# Generated by Django 3.2.13 on 2024-04-09 09:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0073_alter_apphistorymodel_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appcommentmodel',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='Комментарий'),
        ),
    ]
