# Generated by Django 3.2.13 on 2024-05-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0074_alter_appcommentmodel_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLastUID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.PositiveIntegerField(verbose_name='UID последнего прочитанного сообщения')),
                ('pubdate', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
            ],
        ),
    ]
