# Generated by Django 3.2.13 on 2024-09-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0078_delete_executormodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='appcommentmodel',
            name='edited',
            field=models.BooleanField(default=False, verbose_name='Комментарий был отредактирован'),
        ),
    ]
