# Generated by Django 3.2.13 on 2023-06-27 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spares', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpareModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование')),
                ('sn', models.CharField(max_length=50, verbose_name='Серийный номер')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('barcode', models.ImageField(blank=True, upload_to='barcodes/')),
            ],
            options={
                'verbose_name': 'ЗИП',
                'verbose_name_plural': 'ЗИП',
                'ordering': ['name', 'sn'],
            },
        ),
        migrations.CreateModel(
            name='SparePNModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spares.partnumbermodel', verbose_name='Партномер')),
                ('spare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pnspare', to='spares.sparemodel', verbose_name='Запчасть')),
            ],
            options={
                'verbose_name': 'Партномер',
                'verbose_name_plural': 'Партномера',
                'ordering': ['number'],
            },
        ),
    ]
