# Generated by Django 3.2.13 on 2023-08-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spares', '0002_sparemodel_sparepnmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnumbermodel',
            name='number',
            field=models.CharField(max_length=100, unique=True, verbose_name='Партномер'),
        ),
    ]
