# Generated by Django 3.2.13 on 2023-09-15 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spares', '0003_alter_partnumbermodel_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparemodel',
            name='sn',
            field=models.CharField(max_length=50, unique=True, verbose_name='Серийный номер'),
        ),
    ]
