# Generated by Django 3.2.13 on 2023-09-15 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spares', '0004_alter_sparemodel_sn'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sparepnmodel',
            unique_together={('number', 'spare')},
        ),
    ]
